#
# Makefile for the DRI Shared memory and Inter Core Queue Driver
#

ifeq ($(CONFIG_ARCH_FEROCEON_MV78XX0),y)
	include $(TOPDIR)/arch/arm/mach-feroceon-mv78xx0/config/mvRules.mk
endif

shared_mem-objs := shared_mem.o

